sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gT+QtDIGsudFPmunwnj8mlTZ3n9ztSiU1SCALS6Dbp/kxqcbeAfM0gBul9oW1WxeGDy3W7uvNz5RQQDgpEWlPL2/4ykG2sbce79xVsTJsDa6bm/p7CTqUnQ3kMWou7Rpu3HZdtHGasLsCRcGza3/1jGmoHpsgVLxzMZ6vAXe4LwMnMuCwX2zpHeNGDp9UG01oDi0Fz7zcYfJgBh/MIxL/AeHABUT/wj28NZLw4JgVBTwYHIbUNkCl1dv24Ls0h8cMf4bwMNc8RGU0ttlu1LcVDURXU5dLXlKDpv9YEdvihKc9rptIdtMQMrPCwhjZnj5WEkNQhwyodS6Z+r/DjmkoEfAp8rw+ZTVSNJFT+CHgKHafs2zD5rGq25NftX5eIL/S7QiWC1CSOl0HLQgWIqwaCA0J2zYuW1P8RpiwxS9eTbPbb2CgijoPNWh3P5VlSpKRvNpAFCNTK9k/Q6JsB92nx/Af55p9Rf7jrGSa5RTU1TzNWcloYRIoStIxRQNAfReRYHGb0NSdf5RZNzTH6vpKvlno6ydxma5mUFq3pTzaCbBBpbOoCVhHwAOVBs01ARAidtaaXFKa8H2gIS+JZF528lv8Gk3yfYl4LcnLl1o3XU15a/4QevyQ3AswJbIcK669MDC9vIShH1L7w5jQdRzQrdmJk6N+96jTcZlmAW2t44=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Memoirs-of-Louis-XIV-and-His-Court-and-of-the-Regency---Volume-10_3869
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy